# HESNO
hostname: CUCM-{{ pc_num }}
password: pass
secret: pass


# INTERFACES
interfaces:
  - name: 'FastEthernet0/0'
    desc: 'GATEWAY'
    ip: '10.{{ pc_num }}.100.8'
    mask: '255.255.255.0'


# ANALOG PHONES
add_dn: ' '
dn_entry: '{{ add_dn }}{{ pc_num }}'

analog_phones:
  - directory_number: '{{ dn_entry }}00'
    port: '0/0/0'
  - directory_number: '{{ dn_entry }}01'
    port: '0/0/0'
  - directory_number: '{{ dn_entry }}02'
    port: '0/0/0'
  - directory_number: '{{ dn_entry }}03'
    port: '0/0/0'


# TELEPHONY
telephony:
  auto_assign: False
  auto_reg_ephone: False
  max_ephones: '5'
  max_directory_numbers: '20'
  tftp_server: '10.{{ pc_num }}.100.8'
  sccp_port: '2000'
  dn_list:
    - id: '1'
      number: '{{ dn_entry }}11'
    - id: '2'
      number: '{{ dn_entry }}22'
    - id: '3'
      number: '{{ dn_entry }}33'
    - id: '4'
      number: '{{ dn_entry }}44'
    - id: '5'
      number: '{{ dn_entry }}55'
    - id: '6'
      number: '{{ dn_entry }}66'
    - id: '7'
      number: '{{ dn_entry }}77'
    - id: '8'
      number: '{{ dn_entry }}88'
    - id: '9'
      number: '{{ dn_entry }}99'
    - id: '10'
      number: '{{ dn_entry }}89'

ephones:
  - id: '1'
    mac: '{{ ephone1_mac }}'
    type: '8945'
    buttons: '1:1 2:2 3:3 4:4'
    restart: True
  - id: '2'
    mac: '{{ ephone2_mac }}'
    type: '8945'
    buttons: '1:5 2:6 3:7 4:8'
    restart: True


# VIDEO CALLS
video_conf:
  - id: '1'
    codec: 'h323'
  - id: '2'
    codec: 'h323'  


# INCOMING CALLS
incoming_calls:
  allow_all: True


# OUTGOING CALLS
outgoing_calls:
  - id: '11'
    destination_pattern: '{{ add_dn }}11..'
    target: '10.11.100.8'
    codec: 'g711ulaw'
  - id: '12'
    destination_pattern: '{{ add_dn }}12..'
    target: '10.12.100.8'
    codec: 'g711ulaw'
  - id: '21'
    destination_pattern: '{{ add_dn }}21..'
    target: '10.21.100.8'
    codec: 'g711ulaw'
  - id: '22'
    destination_pattern: '{{ add_dn }}22..'
    target: '10.22.100.8'
    codec: 'g711ulaw'
  - id: '31'
    destination_pattern: '{{ add_dn }}31..'
    target: '10.31.100.8'
    codec: 'g711ulaw'
  - id: '32'
    destination_pattern: '{{ add_dn }}32..'
    target: '10.32.100.8'
    codec: 'g711ulaw'
  - id: '41'
    destination_pattern: '{{ add_dn }}41..'
    target: '10.41.100.8'
    codec: 'g711ulaw'
  - id: '42'
    destination_pattern: '{{ add_dn }}42..'
    target: '10.42.100.8'
    codec: 'g711ulaw'
  - id: '51'
    destination_pattern: '{{ add_dn }}51..'
    target: '10.51.100.8'
    codec: 'g711ulaw'
  - id: '52'
    destination_pattern: '{{ add_dn }}52..'
    target: '10.52.100.8'
    codec: 'g711ulaw'
  - id: '61'
    destination_pattern: '{{ add_dn }}61..'
    target: '10.61.100.8'
    codec: 'g711ulaw'
  - id: '62'
    destination_pattern: '{{ add_dn }}62..'
    target: '10.62.100.8'
    codec: 'g711ulaw'
  - id: '71'
    destination_pattern: '{{ add_dn }}71..'
    target: '10.71.100.8'
    codec: 'g711ulaw'
  - id: '72'
    destination_pattern: '{{ add_dn }}72..'
    target: '10.72.100.8'
    codec: 'g711ulaw'
  - id: '81'
    destination_pattern: '{{ add_dn }}81..'
    target: '10.81.100.8'
    codec: 'g711ulaw'
  - id: '82'
    destination_pattern: '{{ add_dn }}82..'
    target: '10.82.100.8'
    codec: 'g711ulaw'
  - id: '91'
    destination_pattern: '{{ add_dn }}91..'
    target: '10.91.100.8'
    codec: 'g711ulaw'
  - id: '92'
    destination_pattern: '{{ add_dn }}92..'
    target: '10.92.100.8'
    codec: 'g711ulaw'

# ROUTING
ospf:
  - id: '1'
    router_id: '10.{{ pc_num }}.100.8'
    networks:
      - network: '10.{{ pc_num }}.100.0'
        wild_mask: '0.0.0.255'
        area: '0'

# IVRS
ivrs:
  id: '69'
  destination_pattern: '{{ dn_entry }}69'
  target: '10.{{ pc_num }}.100.1'
  codec: 'g711ulaw'
  music_on_hold: ' "flash:/en_bacd_music_on_hold.au" '
  hunts:
    hunt_1: '{{ dn_entry }}00'
    hunt_2: '{{ dn_entry }}01'
    hunt_3: '{{ dn_entry }}33'
    hunt_4: '{{ dn_entry }}77'



